### ISSUE TITLE
about.mdを更新

### ISSUE THREAD

**Issue by ToshikiYamamoto** [ajike/ajike.github.io#2]

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
こちらのPRチームにテキストいただいくイメージでよいでしょうか。

**Comment by ToshikiYamamoto** [comment]
@matsunaga いえ、これはPRチームとは別のイメージです。

内容的には、このブログについて、なので
- ブログの説明
- 会社の説明
- 必要であればメンバーの説明
とかですかね。

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。

**Comment by ToshikiYamamoto** [comment]
@matsunaga 
必要であれば、他から内容引っ張ってきていただいて大丈夫です！

**Comment by matsunaga** [comment]
@ToshikiYamamoto
かしこまりました。
