### ISSUE TITLE
記事詳細にfacebookボタン追加

### ISSUE THREAD

**Issue by matsunaga** [ajike/ajike.github.io#20]
@fff-komatsu 
よろしくお願いします！

# 作業内容
- [ ] Facebookいいねボタンの設置

# 作業期限
2017.08.07

**Comment by fff-komatsu** [comment]
@matsunaga 
シェアは無しにして、「いいね」だけにするPR後ほどお送りします！

**Comment by matsunaga** [comment]
@fff-komatsu 
> シェアは無しにして、「いいね」だけにするPR後ほどお送りします！

ありがとう！

# 追加要望
あともう１つ要望があってカテゴリーと投稿日の表示を横並びにしたい。
時間的に作業可能そう？

今
```
カテゴリー：テスト２
Written on July 18, 2017
```

要望
```
テスト２ | July 18, 2017
```

**Comment by ToshikiYamamoto** [comment]
@matsunaga これクローズで大丈夫ですか？
（PR #21 に追記でシェアはありのままでいいとの記載があったので。）

個人的にはシェアボタンは欲しいです

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
クローズではありません。

> 個人的にはシェアボタンは欲しいです
かしこまりました。

@fff-komatsu 
シェアボタンありでお願いいたします。

**Comment by ToshikiYamamoto** [comment]
@matsunaga 
そうなんですね！下記のいいね、シェアボタンとは別ですか？
<img width="818" alt="screen shot 2017-08-01 at 18 10 08" src="https://user-images.githubusercontent.com/12194483/28817939-b6a1ef00-76e4-11e7-889b-8e5d4279f329.png">

**Comment by fff-komatsu** [comment]
@ToshikiYamamoto 
@matsunaga 
シェアボタンあり = 現状のまま 
という認識ですが、issueの内容合っていますか？

問題なければ縦にずれてるのだけ直すPR送ります

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
キャプチャ内のシェアボタンがシェアボタンの認識です。

> 問題なければ縦にずれてるのだけ直すPR

こちらでよいと思っています。

**Comment by fff-komatsu** [comment]
@matsunaga 
ありがとうございますmm

**Comment by ToshikiYamamoto** [comment]
> こちらでよいと思っています。

ですです１

**Comment by fff-komatsu** [comment]
<img width="813" alt="2017-08-02 13 05 31" src="https://user-images.githubusercontent.com/14340670/28857300-594a69c8-7783-11e7-9de6-afa2c39bed24.png">

**Comment by ToshikiYamamoto** [comment]
💯

**Comment by fff-komatsu** [comment]
@matsunaga 
あとは松永さんのイメージ合っていましたら下記マージしますね
https://github.com/ajike/ajike.github.io/pull/50

**Comment by fff-komatsu** [comment]
@matsunaga 
マージされたのでcloseします
