### ISSUE TITLE
カテゴリー機能にカテゴリごとの絞込み機能を追加

### ISSUE THREAD

**Issue by matsunaga** [ajike/ajike.github.io#23]
# 内容
カテゴリー表示をリンクに変更
リンク押下後、カテゴリーに属している記事一覧表示

# 理由
なし

# 期限
2017.09.07

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
「絞込み機能」は検索を意味しておりますでしょうか。

**Comment by ToshikiYamamoto** [comment]
あ、そうではなくて、
> 内容
カテゴリー表示をリンクに変更
リンク押下後、カテゴリーに属している記事一覧表示

これを言い換えただけのつもりでした。
日本語下手ですみません。

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
ご確認ありがとうございます。
失礼いたしました。
かしこまりました。


- [ ] mdでのカテゴリー設定で「AWS Lambda」で１つのカテゴリにできるか調査

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
`feature/cat-list`ブランチをチェックアウトしていただき、機能のご確認をお願いいたします。
よろしくお願いいたします。

**Comment by ToshikiYamamoto** [comment]
@matsunaga これってPRにしない方がいいんでしたっけ？

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
PRにしていただいても問題ありません。
ただ修正あるならPR前に作業した方がわかりやすいかなと考えております。
PRにしますでしょうか。

**Comment by ToshikiYamamoto** [comment]
@matsunaga 
処理が完成したのであれば、PR上でやりとりした方が良いと思っています！

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。
では先に市川さんにデザイン見ていただき、修正あれば修正していただくようにいたします。
よろしくお願いいたします。

**Comment by ToshikiYamamoto** [comment]
@matsunaga デザインもPRでやりたいです！

**Comment by matsunaga** [comment]
@miupink 
feature/cat-listブランチをチェックアウトしていただき、デザインのご確認をお願いいたします。
修正がある場合、そのまま修正していただいて問題ありません。
よろしくお願いいたします。

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。

@miupink 
失礼いたしました。

**Comment by ToshikiYamamoto** [comment]
@matsunaga 
このコメントによるとGithubはホワイトリストに追加されたプラグイン以外動作させないようにしてるらしいです。
https://github.com/jekyll/jekyll/issues/325#issuecomment-1135567

プラグインのホワイトリスト
https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb

残念ですねー。
いったん凍結します。

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
色々作業していただきありがとうございます。
調査が足りず、失礼いたしました。
