### ISSUE TITLE
aboutページにブログ説明用テキストを追加

### ISSUE THREAD

**Issue by fff-komatsu** [ajike/ajike.github.io#24]
aboutページにajikeの紹介以外にもブログに関する説明テキストを入れたい

**Comment by matsunaga** [comment]
@fff-komatsu 
ありがとう！
入れてほしい！

**Comment by fff-komatsu** [comment]
@ToshikiYamamoto 
砕けたかテスト

**Comment by ToshikiYamamoto** [comment]
@fff-komatsu 
ごめんこれ結構重要なのでよろしくです。

**Comment by fff-komatsu** [comment]
@matsunaga 
@ToshikiYamamoto 
これ自分で出しておいてあれですが、あまり書くことがないですね・・
下記みたいな感じで考えましたが、いかがですか？

ユーザー体験のデザインを強みとするアジケの中で日々開発しているエンジニア達によるブログです。<br>
現在はサービス開発から受託開発まで様々なプロジェクトにおいて実装を経験しており、そうしたエンジニアリングの知見や、UXデザイン会社のエンジニアが日々どのような活動をしているのかを発信していきます。<br>

**Comment by fff-komatsu** [comment]
リリース完了につきclose
