### ISSUE TITLE
「この記事を書いた人」改修

### ISSUE THREAD

**Issue by fff-komatsu** [ajike/ajike.github.io#25]
aboutページにメンバーの紹介を掲載する。
イメージとしては、アジケサイトのメンバーページで使っているイラストとテキストを表示する感じ

**Comment by ToshikiYamamoto** [comment]
イラストとか写真は嫌。

**Comment by fff-komatsu** [comment]
@matsunaga 
これですがテキスト情報だけなら「この記事を書いた人」の部分に詳細テキストを追加するだけでもよいのでは？と思ったのですが、いかがでしょうか？

**Comment by matsunaga** [comment]
@fff-komatsu 
もちろんOK！
これは「Aboutページとは別に」という認識でいいのかな？
それともAboutページにも追加するけど、「この記事を書いた人」にも追加するという認識かな？

# 「この記事を書いた人」への追加
記事毎に自分の紹介テキストを入力するのは大変なので、何かしたら方法を考えないといけないね。

**Comment by fff-komatsu** [comment]
@matsunaga 
もともとはメンバーページでも作ろうかと思っていたのですが、あまり情報量もないので無しでいいかなぁという感じですmm

そしたら「この記事を書いた人」をincludeする形にするのどうでしょう？

**Comment by matsunaga** [comment]
@fff-komatsu 
> もともとはメンバーページでも作ろうかと思っていたのですが、あまり情報量もないので無しでいいかなぁという感じ

メンバーページだったんだ！
勝手にAboutページに4人分三行つづくらいのテキストとかが追加になるイメージしてた。
メンバーページ新規作成だと小松くんの言うように情報量すくないよね。

> そしたら「この記事を書いた人」をincludeする形にするのどうでしょう？

最高だと思う！


# 結論
下記の認識でいいかな。

- Aboutページへの追加はしない
- メンバーページの作成はしない
- 「この記事を書いた人」の改修

もし問題ないようなら「この記事を書いた人」の改修で進行してもらって、このIssuesのタイトルを修正してもらえると助かる！

**Comment by fff-komatsu** [comment]
承知しました！

**Comment by matsunaga** [comment]
@fff-komatsu
ありがとうー、助かる！
よろしく！

**Comment by fff-komatsu** [comment]
リリース完了
