### ISSUE TITLE
ページャ

### ISSUE THREAD

**Issue by matsunaga** [ajike/ajike.github.io#26]

**Comment by ToshikiYamamoto** [comment]
@matsunaga 
参考ですー
http://genjiapp.com/blog/2013/11/17/jekyll-pagination.html

**Comment by ToshikiYamamoto** [comment]
本家のDocsの方が情報多いですけど。
http://jekyllrb.com/docs/pagination/#Beware

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
ありがとうございます。
参考にいたします。
