### ISSUE TITLE
ブログタイトル下のテキスト

### ISSUE THREAD

**Issue by fff-komatsu** [ajike/ajike.github.io#28]
ブログタイトル下のテキストを考える
「UXデザインを強みとするajikeの〜〜」みたいな

**Comment by matsunaga** [comment]
@fff-komatsu 
@miupink 
下記どうでしょうか。

UXデザイン会社のユーザー視点エンジニアリング

**Comment by matsunaga** [comment]
@fff-komatsu 
@miupink 
下記でどうでしょうか。
いろいろなブログを山本くんに検索していただきました。

アジケ開発者ブログ

**Comment by fff-komatsu** [comment]
@matsunaga 
シンプルでいいと思います！
ちなみに「UX」とか「サービス開発」とかSEOを意識したキーワードを外したのは何か背景がありましたか？

**Comment by miupink** [comment]
@matsunaga 
両方を合わせて以下とかどうですか！
UXデザイン会社アジケの開発者ブログ

**Comment by matsunaga** [comment]
@fff-komatsu 
「他の開発ブログがそうだった」が背景です。

@miupink 
両方合わせいいですね！
ありがとうございます。

@ToshikiYamamoto 
@fff-komatsu 

UXデザイン会社アジケの開発者ブログ

どうでしょうか。

**Comment by ToshikiYamamoto** [comment]
@matsunaga いいと思いますよー

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
ありがとうございます！

**Comment by matsunaga** [comment]
@fff-komatsu 
確認よろしく！

**Comment by fff-komatsu** [comment]
@matsunaga 

> UXデザイン会社アジケの開発者ブログ
で決定でOKでしたか？？

**Comment by fff-komatsu** [comment]
@matsunaga 
#55 にて変更PR出していますので、ご確認よろしくお願い致しますmm

**Comment by matsunaga** [comment]
@fff-komatsu 
マージ！

**Comment by fff-komatsu** [comment]
@matsunaga 
ありがとうございます！
issueクローズします
