### ISSUE TITLE
記事詳細FBシェアのOGP画像は記事メインビジュアルにする

### ISSUE THREAD

**Issue by fff-komatsu** [ajike/ajike.github.io#30]
facebookのいいねのOGP画像として記事のメインビジュアルを引っ張ってくる
可能であれば、指定なし時はデフォルトとして共通のOGP画像を選択するようにしたい

**Comment by ToshikiYamamoto** [comment]
@fff-komatsu 
> 可能であれば、指定なし時はデフォルトとして共通のOGP画像を選択するようにしたい

これさ、指定なしの時は同じ画像ではなくて、
- 背景＋記事ごとに設定した文字
とかにしたいなー

**Comment by fff-komatsu** [comment]
@ToshikiYamamoto 
画像をcanvasで生成するってことですか？

**Comment by ToshikiYamamoto** [comment]
@fff-komatsu 
それできたらすごいなー笑
別に画像と同じサイズの箱に普通のテキストがいい感じで記載されているとかでいいよ

**Comment by fff-komatsu** [comment]
@ToshikiYamamoto 
楽しそうですね、一緒にやりましょうか

**Comment by ToshikiYamamoto** [comment]
あ、間違えたこれOGPか。笑

**Comment by ToshikiYamamoto** [comment]
記事のメインビジュアルの話やと思った

**Comment by ToshikiYamamoto** [comment]
OGPはデフォルト画像で大丈夫す。笑

**Comment by fff-komatsu** [comment]
あれ、はい笑

**Comment by fff-komatsu** [comment]
@matsunaga 
リリース完了につきcloseします
