### ISSUE TITLE
Gtihubイシュー運用ルール

### ISSUE THREAD

**Issue by matsunaga** [ajike/ajike.github.io#35]
# 内容
Issuesの運用方法の確立

# 理由
運用改善のため。

# 期限
2017.09.07

**Comment by ToshikiYamamoto** [comment]
@matsunaga これとか別にPhase１じゃなくてもいいです！

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。

@fff-komatsu 
Phase2になりました。

**Comment by fff-komatsu** [comment]
# Pipelineの設定について
## New Issues
対応・実施がまだ決まっていないissue

## TODO
対応・実施が決定したissue

## In Progress
対応中・実装中のissue

## Pull Requested
プルリク済みのissue

## Confirmed
プルリクでLGTMもらってリリース待機中のissue

**Comment by ToshikiYamamoto** [comment]
@fff-komatsu 
Pipelineについては、誰がどのタイミングで変更するかを決めといてくれる？
あと、PRとIssueのテンプレートもお願いしたいです。
Pipelineって日本語使えるんやったら日本語の方がわかりやすいかもよ
（使えんかったらごめん）

**Comment by fff-komatsu** [comment]
@ToshikiYamamoto 
テンプレート反映したので、項目とかアップデートしたものがあれば言って下さい

**Comment by ToshikiYamamoto** [comment]
@fff-komatsu 
Issueには、概要ではなくて詳細を記載してほしい！

> 別途必要なリリース作業

これは必要ないと思うけどいるんかな？

> 変更内容

これはIssueがあればIssue番号だけで良いよ

＃の数がPRとIssueで違うのはがきになる

くらいかな！

**Comment by fff-komatsu** [comment]
@matsunaga 
@ToshikiYamamoto 
こちら対応完了して、ドキュメントのアップロードも完了したのでcloseします

**Comment by ToshikiYamamoto** [comment]
@fff-komatsu 
周知までしといてね
