### ISSUE TITLE
記事の著者を表示したい

### ISSUE THREAD

**Issue by ToshikiYamamoto** [ajike/ajike.github.io#56]
## 内容
記事の著者を簡単に表示できるようにしたいです。

## 仕様イメージ
1. posts/xxxx.mdで著者を登録（登録方法は簡単な方がいい）
2. 著者の情報が投稿の末尾に表示される
こんな感じ↓
<img width="712" alt="screen shot 2017-08-02 at 17 55 18" src="https://user-images.githubusercontent.com/12194483/28865740-d66bbd26-77ab-11e7-8b84-299ee20533bb.png">
3. 投稿した人の記事一覧が見れる

的な

**Comment by ToshikiYamamoto** [comment]
フェーズとアサインはとりあえず適当に振ってますんで、この後はよろしくです。

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。

> 3. 投稿した人の記事一覧が見れる
的な

こちらはPhase2にいたします。

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
ご確認をお願いいたします。
画像はGithubの画像を表示いたします。
https://ajike.github.io/%E3%83%86%E3%82%B9%E3%83%88%E6%8A%95%E7%A8%BF%E3%81%A7%E3%81%99%EF%BC%92/

@miupink 
@fff-komatsu 
修正ください。
