### ISSUE TITLE
記事を書いた人一覧ページ

### ISSUE THREAD

**Issue by matsunaga** [ajike/ajike.github.io#57]
# 内容
https://github.com/ajike/ajike.github.io/issues/56

> 3. 投稿した人の記事一覧が見れる

# 理由
# 期限
2017.09.07

**Comment by ToshikiYamamoto** [comment]
@matsunaga 
これも #23 と同様の理由で難しそうな印象なので一旦凍結で大丈夫です。

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。
