### ISSUE TITLE
GAタグ設定

### ISSUE THREAD

**Issue by matsunaga** [ajike/ajike.github.io#6]
GAタグ設定を設定いたします。

**Comment by matsunaga** [comment]
ajike.inc@gmail.com

**Comment by matsunaga** [comment]
市川さん@miupink
小松くん@fff-komatsu 

GTMタグは生成したのですが、
- [ ] GTM管理画面の設定
- [ ] ファイルへの組み込み

が終わっていません。
GTM設定が得意な方に助けてもらいたいです。

---
- Googleアカウント情報
https://github.com/ajike/ajike.github.io/issues/6#issuecomment-315945905

**Comment by ToshikiYamamoto** [comment]
@matsunaga この情報ってWikiに入れる想定です？

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
いつもはWikiには記載しないのですが、どうしましょう。

**Comment by ToshikiYamamoto** [comment]
承知しました！
ログイン関連のアカウント情報はChatworkに入れるようにしましょうか。

**Comment by ToshikiYamamoto** [comment]
@matsunaga

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。

**Comment by ToshikiYamamoto** [comment]
@miupink これリリースされてたらクローズしちゃってくださいー
