### ISSUE TITLE
一覧での文言を本文の頭出しではなく、page.descriptionに変更

### ISSUE THREAD

**Issue by ToshikiYamamoto** [ajike/ajike.github.io#82]
## 内容
下記のように一覧での文言が本文の頭出しになっているが、本文の頭出しは大抵自己紹介になってしまいそうなので、
pageに記載しているdescriptionの内容に変更したい
<img width="594" alt="screen shot 2017-08-21 at 13 07 21" src="https://user-images.githubusercontent.com/12194483/29503335-c3653868-8671-11e7-84a2-0280e58b7f1f.png">

## 理由
回遊率を高めるため

**Comment by matsunaga** [comment]
@ToshikiYamamoto 
かしこまりました。

**Comment by ToshikiYamamoto** [comment]
追記です

切り分けとして、
page.description | page.excerpt | strip_html
ですかね。
ルール上page.descriptionが含まれないパターンはないはずですが、一応このようにしたいです。

**Comment by matsunaga** [comment]
@ToshikiYamamoto
かしこまりました。

**Comment by ToshikiYamamoto** [comment]
@matsunaga 上記誤記ございましたので修正します。
誤）
```
page.description | page.excerpt | strip_html
```

正）
```
page.description 
もしくは
page.excerpt | strip_html
```

ですね。

**Comment by ToshikiYamamoto** [comment]
必要であれば
truncate: 1000
などで文字数制限つけてもらえればいいと思います

**Comment by matsunaga** [comment]
@ToshikiYamamoto
かしこまりました。

**Comment by ToshikiYamamoto** [comment]
本番確認しました。
最高でした！迅速な対応ありがとうございます！
